application: gae-django-py-weibo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: resources
  
- url: /.*
  script: main.app #a WSGI application in the main module's global scope

libraries:  
- name: django
  version: "1.5"
  
- name: MySQLdb
  version: "1.2.4b4"
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'weibo.settings'
  
builtins:
- django_wsgi: on

